In [5]:
cd ..

/Users/rafaelkovashikawa/Downloads/projects/DataDive25/Team_Projects/JobsLens_AI

/Users/rafaelkovashikawa/Downloads/projects/Fall-Detection-Exercise/env/lib/python3.9/site-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [8]:
!ls

dashboard      docs           project.md     visualizations
data           notebooks      src

In [1]:
import pandas as pd

In [58]:
join_dataset = pd.read_excel('data/join_dataset.xlsx')
join_dataset.columns = join_dataset.iloc[2]
join_dataset = join_dataset.iloc[3:]
# Normalize column names: lowercase, replace spaces with underscores, remove special characters
join_dataset.columns = (
    join_dataset.columns
        .str.strip()
        .str.lower()
        .str.replace(' ', '_')
        .str.replace(r'[^\w_]', '', regex=True)
)

# data quality flags filter
join_dataset = join_dataset[join_dataset['percentile_100__max_share_of_flags'].astype(float) < 30]

# filter subsample for 'all' only
join_dataset = join_dataset[join_dataset['subsample'] == 'Urban']

# filter the dataset to only include the latest date for each country
join_dataset['year_of_survey'] = join_dataset['year_of_survey'].astype(int)
latest_date = join_dataset.groupby('country_code', as_index=False)['year_of_survey'].max()
# merge the latest date with the dataset so we can filter the dataset to only include the latest date for each country  
join_dataset = join_dataset.merge(latest_date, on=['country_code', 'year_of_survey'], how='inner')

join_dataset.head()

,country_name,country_code,region_code,subsample,income_level_name,income_level_code,year_of_survey,survey_data_source,survey_type,total_population,...,mean_age_of_worker_in_agriculture_between_1564,mean_age_of_worker_in_industry_between_1564,mean_age_of_worker_in_services_between_1564,mean_age_of_wage_worker_between_1564,mean_age_of_selfemployed_or_unpaid_worker_between_1564,mean_age_of_employer_between_1564,total_flags_in_survey,percentile_100__max_total_flags,flags_over_max_number_of_flags,percentile_100__max_share_of_flags
0,Belize,BLZ,LCN,Urban,Upper middle income,UMC,1999,BLZ_1999_I2D2_LFS.dta,I2D2,112704,...,38.347889,34.789536,34.496964,32.482666,39.642788,42.208805,45,28,0.038927,24
1,Botswana,BWA,SSF,Urban,Upper middle income,UMC,2009,BWA_2009_I2D2_BCWIS.dta,I2D2,1020090.051324,...,37.457848,34.752403,35.863003,35.093868,37.406166,41.09425,26,6,0.02381,5
2,China,CHN,EAS,Urban,Upper middle income,UMC,2013,CHN_2013_I2D2_CHIP.dta,I2D2,734919999.898438,...,47.628853,38.639542,38.936691,38.493694,42.384361,42.302216,35,14,0.030594,12
3,Cameroon,CMR,SSF,Urban,Lower middle income,LMC,2007,CMR_2007_I2D2_ECAM3.dta,I2D2,8600020,...,32.370041,31.635408,32.708305,33.755219,31.624329,37.784378,33,11,0.027966,9
4,Czechia,CZE,ECS,Urban,High income,HIC,2007,CZE_2007_I2D2_EUROSILC.dta,I2D2,5973765.096436,...,44.891968,41.141079,40.914062,40.728027,42.404243,44.235786,42,23,0.036713,21

In [64]:
latest_date[latest_date['country_code'] == 'USA']

Empty DataFrame
Columns: [country_code, year_of_survey]
Index: []

In [59]:
hai_data = pd.read_csv('data/hai_full_database.csv')

hai_data.columns = hai_data.columns.str.strip().str.lower().str.replace(' ', '_').str.replace(r'[^\w_]', '', regex=True)

hai_data.head()

,publishyear,countryname,countrygroup,code,country,region,incomegroup,population,number_of_total_journal_publications,number_of_total_conference_publications,...,norm_pc_internet_speed_median_download_mbps_display,norm_pc_internet_speed_median_download_mbps_calc,unnamed_224,unnamed_225,national_ai_strategy_is_released,pc_national_ai_strategy_is_released,norm_national_ai_strategy_is_released_display,norm_national_ai_strategy_is_released_calc,norm_pc_national_ai_strategy_is_released_display,norm_pc_national_ai_strategy_is_released_calc
0,2017,Australia,core,AUS,AU,East Asia & Pacific,High income,24592588,999.0,1065.0,...,NaN,NaN,NaN,NaN,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000
1,2017,Austria,core,AUT,AT,Europe & Central Asia,High income,8797566,261.0,379.0,...,NaN,NaN,NaN,NaN,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000
2,2017,Belgium,core,BEL,BE,Europe & Central Asia,High income,11375158,232.0,283.0,...,NaN,NaN,NaN,NaN,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000
3,2017,Brazil,core,BRA,BR,Latin America & Caribbean,Upper middle income,204703445,636.0,876.0,...,NaN,NaN,NaN,NaN,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000
4,2017,Canada,core,CAN,CA,North America,High income,36545075,1058.0,1282.0,...,NaN,NaN,NaN,NaN,1.0,2.740000e-08,100.0,100.0,15.072384,15.072384

In [ ]:
Country codes in both datasets: {'CHL', 'PRT', 'DEU', 'GBR', 'UGA', 'PHL', 'BRA', 'ZAF', 'POL', 'ROU', 'TUR', 'ITA', 'IRL', 'LTU', 'GRC', 'CHN', 'FRA', 'KOR', 'URY', 'LVA', 'BGD', 'LUX', 'IND', 'ARM', 'PAN', 'THA', 'LKA', 'CZE', 'MEX', 'EST', 'CRI', 'IDN', 'ARG', 'ESP'}
Country codes only in join_dataset: {'TLS', 'TCD', 'PRY', 'DOM', 'PER', 'ZWE', 'PAK', 'COL', 'GUY', 'MDG', 'PSE', 'TJK', 'LSO', 'MOZ', 'BFA', 'UZB', 'LCA', 'GTM', 'KHM', 'XKX', 'ZMB', 'VEN', 'SLV', 'GEO', 'RWA', 'TZA', 'BLZ', 'EGY', 'BWA', 'MUS', 'TUN', 'ECU', 'JAM', 'IRQ', 'NIC', 'GMB', 'CIV', 'NER', 'MDV', 'MDA', 'BOL', 'MNG', 'NAM', 'MLI', 'MRT', 'NGA', 'TGO', 'JOR', 'HND', 'SVK', 'STP', 'GHA', 'NPL', 'CMR'}
Country codes only in hai_data: {'JPN', 'NOR', 'BEL', 'ISL', 'CYP', 'VNM', 'HUN', 'DNK', 'CHE', 'KAZ', 'SRB', 'CAN', 'MYS', 'UKR', 'ARE', 'SGP', 'BGR', 'USA', 'SVN', 'KEN', 'ISR', 'NZL', 'SAU', 'RUS', 'SWE', 'NLD', 'AUT', 'BLR', 'FIN', 'HRV', 'MLT', 'AUS'}

Country codes in both datasets: {'CHL', 'PRT', 'DEU', 'GBR', 'UGA', 'PHL', 'BRA', 'ZAF', 'POL', 'ROU', 'TUR', 'ITA', 'IRL', 'LTU', 'GRC', 'CHN', 'FRA', 'KOR', 'URY', 'LVA', 'BGD', 'LUX', 'IND', 'ARM', 'PAN', 'THA', 'LKA', 'CZE', 'MEX', 'EST', 'CRI', 'IDN', 'ARG', 'ESP'}
Country codes only in join_dataset: {'TLS', 'TCD', 'PRY', 'DOM', 'PER', 'ZWE', 'PAK', 'COL', 'GUY', 'MDG', 'PSE', 'TJK', 'LSO', 'MOZ', 'BFA', 'UZB', 'LCA', 'GTM', 'KHM', 'XKX', 'ZMB', 'VEN', 'SLV', 'GEO', 'RWA', 'TZA', 'BLZ', 'EGY', 'BWA', 'MUS', 'TUN', 'ECU', 'JAM', 'IRQ', 'NIC', 'GMB', 'CIV', 'NER', 'MDV', 'MDA', 'BOL', 'MNG', 'NAM', 'MLI', 'MRT', 'NGA', 'TGO', 'JOR', 'HND', 'SVK', 'STP', 'GHA', 'NPL', 'CMR'}
Country codes only in hai_data: {'JPN', 'NOR', 'BEL', 'ISL', 'CYP', 'VNM', 'HUN', 'DNK', 'CHE', 'KAZ', 'SRB', 'CAN', 'MYS', 'UKR', 'ARE', 'SGP', 'BGR', 'USA', 'SVN', 'KEN', 'ISR', 'NZL', 'SAU', 'RUS', 'SWE', 'NLD', 'AUT', 'BLR', 'FIN', 'HRV', 'MLT', 'AUS'}