In [2]:
cd ..

/Users/rafaelkovashikawa/Downloads/projects/DataDive25/Team_Projects/JobsLens_AI

/Users/rafaelkovashikawa/Downloads/projects/Fall-Detection-Exercise/env/lib/python3.9/site-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [3]:
!ls

dashboard            notebooks            src
data                 project.md           visualizations
docs                 skills_gap_navigator

In [4]:
import pandas as pd

In [5]:
join_dataset = pd.read_excel('data/join_dataset.xlsx')
join_dataset.columns = join_dataset.iloc[2]
join_dataset = join_dataset.iloc[3:]
# Normalize column names: lowercase, replace spaces with underscores, remove special characters
join_dataset.columns = (
    join_dataset.columns
        .str.strip()
        .str.lower()
        .str.replace(' ', '_')
        .str.replace(r'[^\w_]', '', regex=True)
)

# data quality flags filter
# join_dataset = join_dataset[join_dataset['percentile_100__max_share_of_flags'].astype(float) < 30]

# filter subsample for 'all' only
join_dataset = join_dataset[join_dataset['subsample'] == 'Urban']

# filter the dataset to only include the latest date for each country
join_dataset['year_of_survey'] = join_dataset['year_of_survey'].astype(int)
latest_date = join_dataset.groupby('country_code', as_index=False)['year_of_survey'].max()
# merge the latest date with the dataset so we can filter the dataset to only include the latest date for each country  
join_dataset = join_dataset.merge(latest_date, on=['country_code', 'year_of_survey'], how='inner')

join_dataset.head()

,country_name,country_code,region_code,subsample,income_level_name,income_level_code,year_of_survey,survey_data_source,survey_type,total_population,...,mean_age_of_worker_in_agriculture_between_1564,mean_age_of_worker_in_industry_between_1564,mean_age_of_worker_in_services_between_1564,mean_age_of_wage_worker_between_1564,mean_age_of_selfemployed_or_unpaid_worker_between_1564,mean_age_of_employer_between_1564,total_flags_in_survey,percentile_100__max_total_flags,flags_over_max_number_of_flags,percentile_100__max_share_of_flags
0,Bulgaria,BGR,ECS,Urban,Upper middle income,UMC,2016,BGR_2016_I2D2_EUROSILC.dta,I2D2,4794982.650103,...,42.561947,43.30962,42.780098,42.765953,43.988277,45.55608,54,40,0.047872,38
1,Bosnia and Herzegovina,BIH,ECS,Urban,Upper middle income,UMC,2007,BIH_2007_I2D2_HBS_V01_M_V02_A.dta,I2D2,1349996.257187,...,43.823017,42.808361,40.805408,41.318096,41.400146,43.098221,86,73,0.090717,71
2,Belize,BLZ,LCN,Urban,Upper middle income,UMC,1999,BLZ_1999_I2D2_LFS.dta,I2D2,112704,...,38.347889,34.789536,34.496964,32.482666,39.642788,42.208805,45,28,0.038927,24
3,Bhutan,BTN,SAS,Urban,Lower middle income,LMC,2017,BTN_2017_I2D2_BLSS.dta,I2D2,222368.418024,...,42.621002,35.408508,35.279533,34.797035,37.181847,40.49416,82,71,0.085774,70
4,Botswana,BWA,SSF,Urban,Upper middle income,UMC,2015,BWA_2015_I2D2_BMTHS_V01_M_V03_A.dta,I2D2,1348300.54,...,40.646545,37.673447,36.802517,36.229225,40.037392,NaN,81,70,0.081,68

In [6]:
hai_data = pd.read_csv('data/hai_full_database.csv')

hai_data.columns = hai_data.columns.str.strip().str.lower().str.replace(' ', '_').str.replace(r'[^\w_]', '', regex=True)

hai_data.head()

,publishyear,countryname,countrygroup,code,country,region,incomegroup,population,number_of_total_journal_publications,number_of_total_conference_publications,...,norm_pc_internet_speed_median_download_mbps_display,norm_pc_internet_speed_median_download_mbps_calc,unnamed_224,unnamed_225,national_ai_strategy_is_released,pc_national_ai_strategy_is_released,norm_national_ai_strategy_is_released_display,norm_national_ai_strategy_is_released_calc,norm_pc_national_ai_strategy_is_released_display,norm_pc_national_ai_strategy_is_released_calc
0,2017,Australia,core,AUS,AU,East Asia & Pacific,High income,24592588,999.0,1065.0,...,NaN,NaN,NaN,NaN,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000
1,2017,Austria,core,AUT,AT,Europe & Central Asia,High income,8797566,261.0,379.0,...,NaN,NaN,NaN,NaN,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000
2,2017,Belgium,core,BEL,BE,Europe & Central Asia,High income,11375158,232.0,283.0,...,NaN,NaN,NaN,NaN,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000
3,2017,Brazil,core,BRA,BR,Latin America & Caribbean,Upper middle income,204703445,636.0,876.0,...,NaN,NaN,NaN,NaN,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000
4,2017,Canada,core,CAN,CA,North America,High income,36545075,1058.0,1282.0,...,NaN,NaN,NaN,NaN,1.0,2.740000e-08,100.0,100.0,15.072384,15.072384

In [8]:
import numpy as np

# get the country codes that are in both datasets
country_codes = join_dataset['country_code'].unique()
country_codes_hai = hai_data['code'].unique()

# get the country codes that are in both datasets
country_codes_both = np.intersect1d(country_codes, country_codes_hai)

# get the country codes that are only in join_dataset
country_codes_only_join = np.setdiff1d(country_codes, country_codes_hai)

# get the country codes that are only in hai_data

In [9]:
country_codes_both

array(['ARG', 'ARM', 'AUT', 'BEL', 'BGD', 'BGR', 'BLR', 'BRA', 'CHE',
       'CHL', 'CHN', 'CRI', 'CYP', 'CZE', 'DEU', 'DNK', 'ESP', 'EST',
       'FIN', 'FRA', 'GBR', 'GRC', 'HRV', 'HUN', 'IDN', 'IND', 'IRL',
       'ISL', 'ITA', 'KAZ', 'KEN', 'KOR', 'LKA', 'LTU', 'LUX', 'LVA',
       'MEX', 'MLT', 'NLD', 'NOR', 'PAN', 'PHL', 'POL', 'PRT', 'ROU',
       'RUS', 'SRB', 'SWE', 'THA', 'TUR', 'UGA', 'UKR', 'URY', 'USA',
       'ZAF'], dtype=object)

In [13]:
hai_data[hai_data['code'].isin(list(country_codes_both))]

,publishyear,countryname,countrygroup,code,country,region,incomegroup,population,number_of_total_journal_publications,number_of_total_conference_publications,...,norm_pc_internet_speed_median_download_mbps_display,norm_pc_internet_speed_median_download_mbps_calc,unnamed_224,unnamed_225,national_ai_strategy_is_released,pc_national_ai_strategy_is_released,norm_national_ai_strategy_is_released_display,norm_national_ai_strategy_is_released_calc,norm_pc_national_ai_strategy_is_released_display,norm_pc_national_ai_strategy_is_released_calc
1,2017,Austria,core,AUT,AT,Europe & Central Asia,High income,8797566,261.0,379.0,...,NaN,NaN,NaN,NaN,0.0,0.000000e+00,0.0,0.0,0.00000,0.00000
2,2017,Belgium,core,BEL,BE,Europe & Central Asia,High income,11375158,232.0,283.0,...,NaN,NaN,NaN,NaN,0.0,0.000000e+00,0.0,0.0,0.00000,0.00000
3,2017,Brazil,core,BRA,BR,Latin America & Caribbean,Upper middle income,204703445,636.0,876.0,...,NaN,NaN,NaN,NaN,0.0,0.000000e+00,0.0,0.0,0.00000,0.00000
5,2017,China,core,CHN,CN,East Asia & Pacific,Upper middle income,1396215000,8514.0,10272.0,...,NaN,NaN,NaN,NaN,1.0,7.160000e-10,100.0,100.0,0.39451,0.39451
6,2017,Denmark,core,DNK,DK,Europe & Central Asia,High income,5764980,141.0,166.0,...,NaN,NaN,NaN,NaN,0.0,0.000000e+00,0.0,0.0,0.00000,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,2024,Sri Lanka,extra,LKA,LK,South Asia,Lower middle income,21916000,57.0,139.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523,2024,Thailand,extra,THA,TH,East Asia & Pacific,Upper middle income,71668011,373.0,251.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
524,2024,Uganda,extra,UGA,UG,Sub-Saharan Africa,Low income,50015092,32.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
525,2024,Ukraine,extra,UKR,UA,Europe & Central Asia,Lower middle income,37860221,478.0,81.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526,2024,Uruguay,extra,URY,UY,Latin America & Caribbean,High income,3386588,13.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
country_codes_both

array(['ARG', 'ARM', 'AUT', 'BEL', 'BGD', 'BGR', 'BLR', 'BRA', 'CHE',
       'CHL', 'CHN', 'CRI', 'CYP', 'CZE', 'DEU', 'DNK', 'ESP', 'EST',
       'FIN', 'FRA', 'GBR', 'GRC', 'HRV', 'HUN', 'IDN', 'IND', 'IRL',
       'ISL', 'ITA', 'KAZ', 'KEN', 'KOR', 'LKA', 'LTU', 'LUX', 'LVA',
       'MEX', 'MLT', 'NLD', 'NOR', 'PAN', 'PHL', 'POL', 'PRT', 'ROU',
       'RUS', 'SRB', 'SWE', 'THA', 'TUR', 'UGA', 'UKR', 'URY', 'USA',
       'ZAF'], dtype=object)